config/routes.rb
Mobile::Application.routes.draw do
  get "home/index"

  root :to => "home#index"

  resources :locations, :asklib, :computers, :events, :mobiledatabases, :renalerts

  match 'feedback' => 'feedback#new', :as => 'feedback', :via => :get
  match 'feedback' => 'feedback#create', :as => 'feedback', :via => :post

end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :body

  validates :name, :email, :body, :presence => { :message => "is required" }
  validates :email, :format => { :message => "is not in a valid format", :with => %r{.+@.+\..+} }, :allow_blank => true

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/asklib_controller.rb
class AsklibController < ApplicationController

  def index
  end

end

app/controllers/computers_controller.rb
class ComputersController < ApplicationController

  def index

    client = Savon::Client.new do
      wsdl.document = "http://labstats1-prod.cc.nd.edu/WebServices/Statistics.asmx?WSDL"
      wsdl.namespace = "http://m.library.nd.edu"
    end

    client.wsse.created_at = Time.now
    client.wsse.expires_at = Time.now + 60

    response = client.request :get_grouped_current_stats do
      soap.element_form_default = :unqualified
    end

    doc = Nokogiri::XML(response.to_xml)
    # Makes life a lot easier to remove...
    doc.remove_namespaces!

    # storing stats as hash within hash
    @stats = Hash.new {|hash, key| hash[key] = Hash.new}

    doc.xpath("//GroupStat").each do |group_stat|

      group_id = group_stat.xpath('.//groupId').text

      in_use_count = group_stat.xpath('.//inUseCount').text

      available_count = group_stat.xpath('.//availableCount').text

      off_count = group_stat.xpath('.//offCount').text

      total_count = group_stat.xpath('.//totalCount').text

      @stats[group_id] = { 'in_use_count' => in_use_count, 'available_count' => available_count, 'off_count' => off_count, 'total_count' => total_count }

    end


    @time = Time.now

  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  require 'rubygems'
  require 'open-uri'
  require 'nokogiri'


  def index

    @items = []

    eventsxml = open("http://#{Rails.configuration.library_host}/events/feed/", "User-Agent" => "Ruby-OpenURI", "Referer" => "http://m.library.nd.edu/")
    doc = Nokogiri::XML(eventsxml)

    doc.xpath("//item").each do |item|

      title = item.xpath('.//title').text
      puts title

      post = item.xpath('.//content:encoded').text
      puts post

      @items << {'title' => title, 'post' => post}

    end


  end

end

app/controllers/feedback_controller.rb
class FeedbackController < ApplicationController

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])

    if @message.valid?
      NotificationMailer.feedback_message(@message).deliver
      redirect_to(root_path, :notice => "Thank you for your feedback!")
    else

      if @message.errors[:email].any?
        flash.now.alert = "Please ensure email is in proper format"
      else
        flash.now.alert = "Feedback is required"
      end

      render :new
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
  end

  def show
     render :action =>  params[:id]
  end

  def hesburgh
  end

  def architecture
  end

  def bic
  end

  def chemistry
  end

  def engineering
  end

  def kkic
  end

  def mathematics
  end

  def radlab
  end

  def vrc
  end

  def map2
  end

  def map
  end

end

app/controllers/mobiledatabases_controller.rb
class MobiledatabasesController < ApplicationController
  def index
  end
end

app/controllers/renalerts_controller.rb
class RenalertsController < ApplicationController
  require "rubygems"
  require "open-uri"

  def index
    @renalerts = open(
      "http://us9.campaign-archive2.com/generate-js/?u=3e737e755493a925f88711b17&fid=8753&show=3",
      "User-Agent" => "Ruby-OpenURI",
      "Referer" => "http://m.library.nd.edu/"
    ).read.to_s
    @renalerts.gsub!(/document\.write\(\"/, "")
    @renalerts.gsub!(/\"\)/, "")
    @renalerts.delete! "\\"
    @renalerts.delete! ";"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/asklib/index.html.erb
<h3>Ask a Librarian</h3>

<div data-role="collapsible-set">

  <div data-role="collapsible" data-mini="true" data-content-theme="b">
    <h5>Chat</h5>
    <div style='margin-left:-10px;'>
      <iframe frameborder="0" style="max-width: 95%; height: 200px; border: 1px solid #dcd5b6;" src="https://libraryh3lp.com/mobile/nd-ask-a-lib@chat.libraryh3lp.com?skin=16575&title=Ask%20a%20Librarian&identity=asklib"></iframe>
    </div>
  </div>

  <div data-role="collapsible" data-mini="true" data-content-theme="b">
    <h5>Phone</h5>
    <a href="tel:5746316258">574-631-6258</a>
  </div>

  <div data-role="collapsible" data-mini="true" data-content-theme="b">
    <h5>Email</h5>
    <a href="mailto:asklib@nd.edu">asklib@nd.edu</a>
  </div>

</div>

app/views/computers/index.html.erb
<h3>Computer Lab Finder</h3>


<div data-role="collapsible-set">

  <div data-role="collapsible" data-mini="true" data-content-theme="b">
    <h4><span style="float: left;">Library 1st Floor:</span> <span style="float: right;"><span class="labstat"><%= @stats['28']['available_count'] %></span> Available</span></h4>
    <div class="indent">
    In Use: <span class="labstat"><%= @stats['28']['in_use_count'] %></span><br />
    Available: <span class="labstat"><%= @stats['28']['available_count'] %></span><br />
    Offline: <span class="labstat"><%= @stats['28']['off_count'] %></span><br />
    Total: <span class="labstat"><%= @stats['28']['total_count'] %></span>
    </div>
  </div>




  <div data-role="collapsible" data-mini="true" data-content-theme="b">
    <h4><span style="float: left;">Library GSU:</span><span style="float: right;"><span class="labstat"><%= @stats['21']['available_count'] %></span> Available</span></h4>
    <div class="indent">
      In Use: <span class="labstat"><%= @stats['21']['in_use_count'] %></span><br />
      Available: <span class="labstat"><%= @stats['21']['available_count'] %></span><br />
      Offline: <span class="labstat"><%= @stats['21']['off_count'] %></span><br />
      Total: <span class="labstat"><%= @stats['21']['total_count'] %></span>
    </div>
  </div>


  <div data-role="collapsible" data-mini="true" data-content-theme="b">
    <h4><span style="float: left;">Mendoza BIC:</span><span style="float: right;"><span class="labstat"><%= @stats['26']['available_count'] %></span> Available</span></h4>
    <div class="indent">
      In Use: <span class="labstat"><%= @stats['26']['in_use_count'] %></span><br />
      Available: <span class="labstat"><%= @stats['26']['available_count'] %></span><br />
      Offline: <span class="labstat"><%= @stats['26']['off_count'] %></span><br />
      Total: <span class="labstat"><%= @stats['26']['total_count'] %></span>
    </div>
  </div>

</div>

<span class="font-small"><%= @time.strftime("As of %m/%d/%y %I:%M %p")%></span>

app/views/events/index.html.erb
  <h3 style='margin-bottom:5px;'>Tours and Workshops</h3>

To register for an event, please visit <%= link_to "the library workshop site", "https://#{Rails.configuration.library_host}/instruction/workshops/", :target => '_blank' %>.
<br /><br />
  <div>
  <ul data-role="listview" data-theme="a" data-divider-theme="b">
    <% @items.each do |item| %>
        <li data-role="list-divider"><%= item['title'] %></li>
        <li style="margin-left:7px; white-space: normal; border-style:none;"><%= raw item['post'] %></li>
    <% end %>
  </ul>
  </div>

app/views/feedback/new.html.erb
<h3>Mobile Site Feedback</h3>

<%= form_for @message, :url => { :action => "create" } do |form| %>

      <% @message.errors.full_messages.each do |msg| %>
          <div class="field_with_errors"><%= msg %></div>
      <% end %>


    <div data-role="fieldcontain no-field-separator">
        <%= form.text_field :name, :"data-mini"=>"true", :"data-theme"=>"b", :"placeholder"=>"Name" %>
    </div>

    <div data-role="fieldcontain no-field-separator">
        <%= form.text_field :email, :"data-mini"=>"true", :"data-theme"=>"b", :"placeholder"=>"Email" %>
    </div>


    <div data-role="fieldcontain no-field-separator">
        <%= form.text_area :body, :"data-mini"=>"true", :"data-theme"=>"b", :"placeholder"=>"Feedback" %>
    </div>

    <%= form.submit "Send" %>

<% end %>

app/views/home/index.html.erb
<div style='padding-top:17px;'>
    <% if flash[:notice] %>
        <%= flash[:notice] %><br /><br />
    <% end %>

  <form action="https://library.nd.edu/utilities/search/ndu/onesearch" method="get">

    <input type="search" name="q" data-mini="true" data-theme="a" title="Search Library Catalog" placeholder="Search Library Catalog" accesskey="s" class="defaultTextActive defaultText" />
    <input type="hidden" name="vid" value="NDU">

  </form>

</div>


<div class="ui-grid-c" style='padding-top:15px;'>

  <div class="ui-block-a icon">
    <%= link_to image_tag("icons/ejournals.png", {:class => "icon"}), "http://ejl.library.nd.edu/" %>
    <br />
    <%= link_to "e-Journals", "http://ejl.library.nd.edu/", :class => "icon" %>
  </div>

  <div class="ui-block-b icon">
    <%= link_to image_tag("icons/articles.png", {:class => "icon"}), "http://xerxes.library.nd.edu/quicksearch/" %>
    <br />
    <%= link_to "Articles", "http://xerxes.library.nd.edu/quicksearch/", :class => "icon" %>
  </div>

  <div class="ui-block-c icon">
    <%= link_to image_tag("icons/atoz.png", {:class => "icon"}), mobiledatabases_path  %>
    <br />
    <%= link_to "Mobile Databases", mobiledatabases_path, :class => "icon" %>
  </div>

  <div class="ui-block-d icon">
    <%= link_to image_tag("icons/chat.png", {:class => "icon"}), { :action=>"index", :controller=>"asklib" }  %>
    <br />
    <%= link_to "Ask a Librarian", { :action=>"index", :controller=>"asklib" }, :class => "icon" %>
  </div>


  <div class="ui-block-a icon">
    <%= link_to image_tag("icons/imac.png", {:class => "icon"}), computers_path  %>
    <br />
    <%= link_to "Computer Finder", computers_path, :class => "icon" %>
  </div>

  <div class="ui-block-b icon">
    <%= link_to image_tag("icons/calendar.png", {:class => "icon"}), events_path  %>
    <br />
    <%= link_to "Events", events_path, :class => "icon" %>
  </div>

  <div class="ui-block-c icon">

    <%= link_to image_tag("icons/clock.png", {:class => "icon"}), locations_path  %>
    <br />
    <%= link_to "Hours & Locations", locations_path, :class => "icon" %>

  </div>

  <div class="ui-block-d icon">
    <%= link_to image_tag("icons/employees.png", {:class => "icon"}), "http://library.nd.edu/utilities/directory/employees" %>
    <br />
    <%= link_to "Employees", "http://library.nd.edu/utilities/directory/employees", :class => "icon" %>
  </div>

  <div class="ui-block-a icon">
    <%= link_to image_tag("icons/program-units.png", {:class => "icon"}), "http://library.nd.edu/utilities/directory/departments" %>
    <br />
    <%= link_to "Programs & Units", "http://library.nd.edu/utilities/directory/departments", :class => "icon" %>
  </div>

  <div class="ui-block-b icon">
    <%= link_to image_tag("icons/subject-librarian.png", {:class => "icon"}), "http://library.nd.edu/utilities/directory/subjects" %>
    <br />
    <%= link_to "Subject Librarians", "http://library.nd.edu/utilities/directory/subjects", :class => "icon" %>
  </div>

  <div class="ui-block-c icon">
    <%= link_to image_tag("icons/nd.png", {:class => "icon"}), "http://m.nd.edu" %>
    <br />
    <%= link_to "Mobile ND", "http://m.nd.edu", :class => "icon" %>
  </div>

  <div class="ui-block-d icon">
    <%= link_to image_tag("icons/renalert.png", {:class => "icon"}),  { :action=>"index", :controller=>"renalerts" } %>
    <br />
    <%= link_to "Renalerts", { :action=>"index", :controller=>"renalerts" }, :class => "icon" %>
  </div>
  <!---->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Hesburgh Libraries Mobile // University of Notre Dame</title>


  <link rel="stylesheet" type="text/css" href="//factotum.library.nd.edu/assets/hours_builder.css">
  <link rel="stylesheet" href="//code.jquery.com/mobile/1.2.0/jquery.mobile-1.2.0.min.css" />
  <%= stylesheet_link_tag "mobile" %>


  <script src="//code.jquery.com/jquery-1.8.2.min.js"></script>
  <script type="text/javascript" src="//factotum.library.nd.edu/assets/hours_builder.js"></script>
  <%= javascript_include_tag "mobile" %>
  <script src="//code.jquery.com/mobile/1.2.0/jquery.mobile-1.2.0.min.js"></script>




<!-- Google Analytics -->
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-2118378-21', 'auto');


$(document).on('pageshow', '[data-role=page], [data-role=dialog]', function (event, ui) {
    try {
        ga('create', 'UA-2118378-21', 'auto');
        if ($.mobile.activePage.attr("data-url")) {
            ga('send', 'pageview', $.mobile.activePage.attr("data-url")); // remove quotes
        } else {
            ga('send', 'pageview');
        }
    } catch (err) {}
});


</script>
<!-- End Google Analytics -->




</head>
<body>

<div data-role="page" data-theme="a" <%= (current_page?(:controller => 'home', :action => 'index')) ? "data-add-back-btn=\'false\'" : "data-add-back-btn=\'true\'" %>>

  <div data-role="header">
    <div class="ui-title">

      <%= link_to_unless_current image_tag("header.png", {:class => "hesburgh-header"}), { :action=>"index", :controller=>"home" }, :"data-role"=>"none" %>

    </div>
  </div>

  <div data-role="content" data-theme="a" style="" class="innerContent">

    <%= yield %>

  </div>

  <div class="taupe_bg">&nbsp;</div>

<div data-role="footer" class="ui-bar" data-position="inline">
  <%= image_tag "hesburgh_mark.png", {:class => "hesburgh-mark"} %>&nbsp;&nbsp;<%= link_to "Full Site", "//#{Rails.configuration.library_host}/?mobile_redirect=false", { :class=>"ui-link", "data-role"=>"none" } %>  |  <%= link_to "Feedback", { :action=>"new", :controller=>"feedback" }, { :class=>"ui-link", "data-role"=>"none" } %>
</div>


</div>
</body>


</html>

app/views/locations/architecture.html.erb
  <div style='margin-left:10px;margin-right:10px;'>

  <h4>Architecture Library</h4>

  <%= image_tag "branches/Bond Hall.jpg", {:class => "branch"} %>

    <div style="font-size:0.95em;">
    117 Bond Hall<br />Notre Dame, IN 46556<br />
    <a href="http://architecture.library.nd.edu/" target="_blank">architecture.library.nd.edu</a><br />
    <img src="/assets/gps.png" style="float:left; width:1.5em;">
    <a href='http://map.nd.edu/#/placemarks/1020/zoom/16/lat/41.7006129982979/lon/-86.238899' target='_blank'>view map</a><br />
    <br />
    Tel: <a href="tel:5746316654">574.631.6654</a><br />
    <a href="mailto:archlib@nd.edu">archlib@nd.edu</a>
    </div>

    <div id="architecture_library_destination" class="font-smaller"></div>



  </div>

app/views/locations/bic.html.erb
  <div style='margin-left:10px;margin-right:10px;'>

  <h4>Mahaffey Business Information Center Library</h4>

  <%= image_tag "branches/Mendoza.jpg", {:class => "branch"} %>

    <div style="font-size:0.95em;">
      L001 Mendoza College of Business<br />Notre Dame, IN 46556<br />
      <a href="http://bic.library.nd.edu/" target="_blank">bic.library.nd.edu</a><br />
    <img src="/assets/gps.png" style="float:left; width:1.5em;">
    <a href='http://map.nd.edu/#/placemarks/1148/zoom/16/lat/41.70074917635271/lon/-86.23908139021303' target='_blank'>view map</a><br />
    <br />
    Tel: <a href="tel:5746319098">574.631.9098</a>
    </div>


    <div id="bic_destination" class="font-smaller"></div>


  </div>

app/views/locations/chemistry.html.erb
  <div style='margin-left:10px;margin-right:10px;'>

  <h4>Chemistry - Physics Library</h4>

  <%= image_tag "branches/Nieuwland.JPG", {:class => "branch"} %>

    <div style="font-size:0.95em;">
    231 Nieuwland Science Hall<br />Notre Dame, IN 46556<br />
    <a href="http://chemistry.library.nd.edu" target="_blank">chemistry.library.nd.edu</a><br />
    <img src="/assets/gps.png" style="float:left; width:1.5em;">
    <a href='http://map.nd.edu/#/placemarks/1050/zoom/16/lat/41.70074917635271/lon/-86.23908139021303' target='_blank'>view map</a><br />
    <br />
    Tel: <a href="tel:5746317203">574.631.7203</a>
    </div>

    <div id="chem_phys_library_destination" class="font-smaller"></div>

   </div>

app/views/locations/engineering.html.erb
  <div style='margin-left:10px;margin-right:10px;'>

  <h4>Engineering Library</h4>

  <%= image_tag "branches/Fitzpatrick.jpg", {:class => "branch"} %>

    <div style="font-size:0.95em;">
    149 Fitzpatrick Hall of Engineering<br />Notre Dame, IN 46556<br />
    <a href="http://engineering.library.nd.edu/" target="_blank">engineering.library.nd.edu</a><br />
    <img src="/assets/gps.png" style="float:left; width:1.5em;">
    <a href='http://map.nd.edu/#/placemarks/1088/zoom/16/lat/41.70074917635271/lon/-86.23908139021303' target='_blank'>view map</a><br />
    <br />
    Tel: <a href="tel:5746316665">574.631.6665</a><br />
    <a href="mailto:engrlib@nd.edu">engrlib@nd.edu</a><br />
    </div>

    <div id="engineering_library_destination" class="font-smaller"></div>


      <div class="font-smaller">* Card swipe access to the library is available for Engineering faculty and students after normal business hours.</div>

  </div>

app/views/locations/hesburgh.html.erb
  <div style='margin-left:10px;margin-right:10px;'>

  <h4>Theodore M. Hesburgh Library</h4>

  <%= image_tag "branches/Library.jpg", {:class => "branch"} %>

    <div style="font-size:0.95em;">
    221 Hesburgh Library<br />Notre Dame, IN 46556<br />
    <img src="/assets/gps.png" style="float:left; width:1.5em;">
    <a href='http://map.nd.edu/#/placemarks/1076/zoom/16/lat/41.705233090036245/lon/-86.2331534470825' target='_blank'>view map</a><br />
    <br />
    Tel: <a href="tel:5746316258">(574) 631-6258</a><br />
    <a href="mailto:asklib@nd.edu">asklib@nd.edu</a>
    </div>


    <br />
    <div id="hesburgh_destination" class="font-smaller"></div>



    <div data-role="collapsible" data-mini="true" data-iconpos="right" data-theme="a" data-content-theme="b">
      <h4>* 24/5 Policy</h4>
          At 10:00pm Sunday night through Thursday night the doors to the library will be locked and access will only be through the east and west concourse doors using a swipe reader. You must swipe your card and enter your pin. Your pin is the month and date of your birth. Upon doing this the doors will release for approximately 8 seconds to allow access or you can press the handicap button which will allow the doors to open.
          <br /><br />
          At 7:00am Monday through Friday the doors will be unlocked and the swipe card reader will be disabled.
          <br /><br />
          The swipe card system is only set up for NDID’s. SMC, HC, and Bethel students must call 631-6350 and the security monitor will come and check ID’s and allow access.
    </div>

      <h4 style="margin-bottom:0px;">Circulation and Course Reserves:</h4>
      <a href="tel:5746316258" class="font-smaller">(574) 631-6318</a>
      <div id="circulation_destination" class="font-smaller"></div>

      <h4 style="margin-bottom:0px;">Computer Lab:</h4>
      <a href="tel:5746316892" class="font-smaller">(574) 631-6892</a>
      <div id="computer_lab_destination" class="font-smaller"></div>

      <h4 style="margin-bottom:0px;">Lower Level Service Desk:</h4>
      <a href="tel:5746312889" class="font-smaller">(574) 631-2889</a>
      <div id="lower_level_service_desk_destination" class="font-smaller"></div>

      <h4 style="margin-bottom:0px;">Medieval Institute:</h4>
      <a href="tel:5746315724" class="font-smaller">(574) 631-5724</a>
      <div id="medieval_destination" class="font-smaller"></div>

      <h4 style="margin-bottom:0px;">Music and Media Services Unit:</h4>
      <a href="tel:5746317438" class="font-smaller">(574) 631-7438</a>
      <div id="music_and_media_destination" class="font-smaller"></div>

      <h4 style="margin-bottom:0px;">Reference Desk:</h4>
      <a href="tel:5746316258" class="font-smaller">(574) 631-6258</a>
      <div id="reference_destination" class="font-smaller"></div>

      <h4 style="margin-bottom:0px;">Special Collections:</h4>
      <a href="tel:5746315610" class="font-smaller">(574) 631-5610</a>
      <div id="special_collection_destination" class="font-smaller"></div>

      <h4 style="margin-bottom:0px;">University Archives:</h4>
      <a href="tel:5746316448" class="font-smaller">(574) 631-6448</a>
      <div id="archives_destination" class="font-smaller"></div>


  </div>

app/views/locations/index.html.erb
<h3>Hours and Locations</h3>
<img src="/assets/gps.png" style="float:left; width:1.5em;"><a href="#" class="popupLink">Locations on campus map</a>

<div data-role="popup" data-history="false" class="popupMap" data-theme="c" data-overlay-theme="a" data-corners="false" data-transition="fade">
  <a href="#" data-rel="back" data-role="button" data-theme="c" data-icon="delete" data-iconpos="notext" class="ui-popup-btn-close ui-btn-left">Close</a>
  <%= image_tag "campus-map.jpg" %>
</div>



<div>
<ul data-role="listview" data-inset="true" data-mini="true" data-theme="a">
  <li><%= link_to "Hesburgh Library", location_path("hesburgh") %></li>
  <li><%= link_to "Architecture Library", location_path("architecture") %></li>
  <li><%= link_to "Mahaffey Business Information Center", location_path("bic") %></li>
  <li><%= link_to "Chemistry/Physics Library", location_path("chemistry") %></li>
  <li><%= link_to "Engineering Library", location_path("engineering") %></li>
  <li><%= link_to "Kellogg Kroc Information Center", location_path("kkic") %></li>
  <li><%= link_to "Timothy O'Meara Mathematics Library", location_path("mathematics") %></li>
  <li><%= link_to "Radiation Chemistry Reading Room", location_path("radlab") %></li>
  <li><%= link_to "Visual Resources Center", location_path("vrc") %></li>
</ul>
</div>

app/views/locations/kkic.html.erb
  <div style='margin-left:10px;margin-right:10px;'>

  <h4>Kellogg Kroc Library Information Center</h4>

  <%= image_tag "branches/Hesburgh Center.jpg", {:class => "branch"} %>

    <div style="font-size:0.95em;">
    318 Hesburgh Center for International Studies<br />Notre Dame, IN 46556<br />
      <a href="http://kkic.library.nd.edu/" target="_blank">kkic.library.nd.edu</a><br />
    <img src="/assets/gps.png" style="float:left; width:1.5em;">
    <a href='http://map.nd.edu/#/placemarks/1142/zoom/16/lat/41.70074917635271/lon/-86.23908139021303' target='_blank'>view map</a><br />
    <br />
    Tel: <a href="tel:5746318534">574.631.8534</a>
    </div>

<div id="kellogg_library_destination" class="font-smaller"></div>

  </div>

app/views/locations/mathematics.html.erb
  <div style='margin-left:10px;margin-right:10px;'>

  <h4>O'Meara Mathematics Library</h4>

    <%= image_tag "branches/Hayes.jpg", {:class => "branch"} %>

    <div style="font-size:0.95em;">
    001 Hayes-Healy Center<br />Notre Dame, IN 46556<br />
    <a href="http://mathematics.library.nd.edu/" target="_blank">mathematics.library.nd.edu</a><br />
    <img src="/assets/gps.png" style="float:left; width:1.5em;">
    <a href='http://map.nd.edu/#/placemarks/1082/zoom/16/lat/41.70074917635271/lon/-86.23908139021303' target='_blank'>view map</a><br />
    <br />
    Tel: <a href="tel:5746317278">574.631.7278</a><br />
    <a href="mailto:mathlib.1@nd.edu">mathlib.1@nd.edu</a>
    </div>

<div id="math_library_destination" class="font-smaller"></div>


  </div>

app/views/locations/radlab.html.erb
  <div style='margin-left:10px;margin-right:10px;'>

  <h4>Radiation Chemistry Reading Room</h4>

    <%= image_tag "branches/Radiation.jpg", {:class => "branch"} %>

    <div style="font-size:0.95em;">
    105 Radiation Research Building<br />Notre Dame, IN 46556<br />
    <a href="http://radlab.library.nd.edu/" target="_blank">radlab.library.nd.edu</a><br />
    <img src="/assets/gps.png" style="float:left; width:1.5em;">
    <a href='http://map.nd.edu/#/placemarks/1077/zoom/16/lat/41.70074917635271/lon/-86.23908139021303' target='_blank'>view map</a><br />
    <br />
    Tel: <a href="tel:5746316163">574.631.6163</a><br />
    <a href="mailto:chemlib.1@nd.edu">chemlib.1@nd.edu</a>
    </div>

    <div id="radiation_destination" class="font-smaller"></div>


  </div>

app/views/locations/vrc.html.erb
  <div style='margin-left:10px;margin-right:10px;'>

  <h4>Visual Resources Center</h4>

    <%= image_tag "branches/Riley Hall.JPG", {:class => "branch"} %>

    <div style="font-size:0.95em;">
    216 Riley Hall<br />Notre Dame, IN 46556<br />
    <a href="http://vrc.library.nd.edu/" target="_blank">vrc.library.nd.edu</a><br />
    <img src="/assets/gps.png" style="float:left; width:1.5em;">
    <a href='http://map.nd.edu/#/placemarks/1021/zoom/16/lat/41.70074917635271/lon/-86.23908139021303' target='_blank'>view map</a><br />
    <br />
    Tel: <a href="tel:5746314273">574.631.4273</a>
    </div>

    <div id="visual_resources_destination" class="font-smaller"></div>
  </div>

app/views/renalerts/index.html.erb
<div class="alerts panel">
  <div class="inner">
    <h3><a href="/archive">REN-ALERTS</a> <a href="//us9.campaign-archive2.com/feed?u=3e737e755493a925f88711b17&id=0799f938e8">
      <img src="/assets/fc-webicon-rss-s.png" width="" style=" vertical-align: top;" alt="">
    </a></h3>

    <style type="text/css">
    <!--
    .display_archive {font-family: arial,verdana; font-size: 12px;}
    .campaign {line-height: 125%; margin: 5px;}
    //-->
    </style>
    <!-- <script language="javascript" type="text/javascript"> -->
      <%= raw @renalerts %>
    <!-- </script> -->

  </div>
</div>